# Generated by Django 3.2.7 on 2021-09-09 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ufcfrontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fighter',
            old_name='division',
            new_name='currentDivision',
        ),
    ]
