# Generated by Django 3.2.7 on 2021-09-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufcfrontend', '0004_fighter_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
