# Generated by Django 3.2.7 on 2021-09-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufcfrontend', '0005_fighter_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fighter',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='fighter',
            name='lastName',
            field=models.CharField(default='first', max_length=100),
            preserve_default=False,
        ),
    ]
